### ISSUE TITLE
ASPLOS '22 | Astraea: Towards QoS-Aware and Resource-Efficient Multi-stage GPU Services

### ISSUE THREAD

**Issue by mental2008** [mental2008/awesome-papers#73]
To appear in ASPLOS '22.

**Comment by gaocegege** [comment]
The paper focuses on GPU microservices. But I am not sure what the GPU microservice is. Does it include GPU encoding/decoding job, gene computing or others?

**Comment by mental2008** [comment]
> The paper focuses on GPU microservices. But I am not sure what the GPU microservice is. Does it include GPU encoding/decoding job, gene computing or others?

You can refer to [the previous version](https://arxiv.org/abs/2005.02088) (Section III. A) in arXiv, which may be slightly different from the camera-ready version.

As far as I know, this work mainly focuses on DL applications such as text-to-image, text-to-video, speech-to-text. It seems to only use the GPU's computing resource and memory. The encoding/decoding capability is unused.

**Comment by gaocegege** [comment]
Gotcha thanks!
